# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker
trigger:
- main
resources:
- repo: self
variables:
- group: vprofilevariables
- name: tag
  value: '$(Build.BuildId)'
  
#pool:
 # Default
stages:
- stage: Sonar_Job
  jobs:
  - job: Sonar_Job
    pool:
      name: 'Azure Pipelines'  # Adjust the agent pool as needed
    steps:
    - checkout: self
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '7.x'
    
    - task: SonarCloudPrepare@1
      inputs:
        SonarCloud: 'Sonar Cloud'
        organization: 'vprofile-action240'
        scannerMode: 'MSBuild'
        projectKey: 'vprofile-action240_vprofile24'
        projectName: 'etickets'
        
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: 'eTickets.sln'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
    - task: SonarCloudAnalyze@1
      inputs:
        jdkVersion: 'JAVA_HOME_17_X64'  # Adjust the JDK version if needed
    

- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      inputs:
        repository: '$(imageRepository)'
        command: 'build'
        Dockerfile: './Dockerfile'
        tags: |
          $(tag)
    - task: ECRPushImage@1
      inputs:
        awsCredentials: 'aws-service-account-name'
        regionName: '$(awsRegion)'
        imageSource: 'imagename'
        sourceImageName: '$(imageRepository)'
        sourceImageTag: '$(tag)'
        repositoryName: '$(imageRepository)'
        pushTag: '$(tag)'