# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker
trigger:
- main
resources:
- repo: self
variables:
- group: vprofilevariables
- name: tag
  value: '$(Build.BuildId)'
  
#pool:
 # Default
stages:
- stage: Sonar_Job
  jobs:
  - job: Sonar_Job
    pool:
      name: 'Azure Pipelines'  # Adjust the agent pool as needed
    steps:
    - checkout: self
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '7.x'
    
    - task: SonarCloudPrepare@1
      inputs:
        SonarCloud: 'Sonar Cloud'
        organization: 'vprofile-action240'
        scannerMode: 'MSBuild'
        projectKey: 'vprofile-action240_vprofile24'
        projectName: 'etickets'
        
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: 'eTickets.sln'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
    - task: SonarCloudAnalyze@1
      inputs:
        jdkVersion: 'JAVA_HOME_17_X64'  # Adjust the JDK version if needed
    

# Stage 2: Build and Push Docker Image to AWS ECR
- stage: Build_and_Push
  displayName: 'Build and Push Docker Image'
  dependsOn: Sonar_Job
  condition: succeeded()
  jobs:
  - job: Build_and_Push_Job
    pool:
      name: Default
    steps:
    - checkout: self

    - script: |
        echo "Build Info:"
        echo "Region: $(awsRegion)"
        echo "Registry: $(containerRegistry)"
        echo "Repository: $(imageRepository)"
        echo "Tag: $(tag)"

        echo "Setting up AWS CLI..."
        aws configure set aws_access_key_id $(AWS_ACCESS_KEY_ID)
        aws configure set aws_secret_access_key $(AWS_SECRET_ACCESS_KEY)
        aws configure set default.region $(awsRegion)

        echo "Authenticating with ECR..."
        aws ecr get-login-password --region $(awsRegion) | docker login --username AWS --password-stdin $(containerRegistry)

        echo "Building Docker image..."
        docker build -t $(containerRegistry)/$(imageRepository):$(tag) .

        echo "Pushing Docker image to ECR..."
        docker push $(containerRegistry)/$(imageRepository):$(tag)

      displayName: 'Build and Push Docker Image to AWS ECR'